// vue/src/components/About.vue
<template>
  <div>
    <b-card border-variant="primary" header-bg-variant="primary" header-text-variant="white">
      <h1 slot="header">
        <fa icon="info-circle" /> &nbsp; About Smilr
      </h1>
      <h2>A microservices &amp; SPA reference / demonstration app</h2>
      <img :src="utilsFaceSVG(faceRating)" class="aboutface animated rubberBand infinite slow" @click="easter">
      <h5>{{ egg }}</h5>

      <hr>

      <b>Version: {{ ver }} (Vue.js)</b><br>
      &copy; Ben Coleman, 2017 - 2019<br>
      Provided under the <a target="_blank" href="https://opensource.org/licenses/MIT">MIT License</a><br><br>
      <b-button size="lg" variant="primary" href="https://smilr.benco.io" target="_blank">
        Project details &amp; source code (GitHub)
      </b-button>

      <hr>

      <pre>
<b>API Endpoint:</b> {{ apiEndpoint }}
<b>Mode:</b> {{ mode }}
<b>Build Info:</b> {{ buildInfo }}

<b>More Details:</b> <a :href="infoUrl" target="_blank">{{ apiEndpoint }}/info</a></pre>
    </b-card>
  </div>
</template>

<script>
import '../assets/css/animate.css'
import utils from '../mixins/utils'

export default {
  name: 'About',

  mixins: [ utils ],

  data: function() {
    return {
      apiEndpoint: this.$config.API_ENDPOINT,
      infoUrl: `${this.$config.API_ENDPOINT}/info`,
      mode: process.env.NODE_ENV,
      buildInfo: process.env.VUE_APP_BUILD_INFO || 'No build info',
      egg: '',
      faceRating: 5,
      ver: require('../../package.json').version
    }
  },

  methods: {
    easter: function() {
      this.egg = 'This is probably where I could put a clever hidden easter egg. But I haven\'t bothered. Bye!'
      this.faceRating--
      if (this.faceRating <= 0) { this.faceRating = 5 }
    }
  }
}
</script>

<style scoped>
.aboutface {
  width: 100px;
}
pre {
  background-color: rgb(228, 228, 228);
  padding: 1rem;
  font-size: 70%;
}
</style>

// angular/src/app/about.component.ts
import { Component } from '@angular/core';
import { ConfigService } from './config.service';
import { environment } from '../environments/environment';
import { isDevMode } from '@angular/core';

@Component({
  templateUrl: './about.component.html'
})

export class AboutComponent {
  public apiEndpoint;
  public secured;
  public devMode;

  constructor(config: ConfigService) { 
    this.apiEndpoint = config.values.API_ENDPOINT;
    this.secured = environment.secured ? "Live mode, admin controls require login" : "Demo mode, admin controls are open";
    this.devMode = isDevMode() ? "Angular dev mode" : "Angular prod mode" ;
  }
}
<div class="panel panel-primary simpleFadeIn">
  <div class="panel-heading">
    <h2 class="panel-title">About</h2>
  </div>
  <div class="panel-body">
    <div class='about'>
        <h2 class="panel-title">A microservices &amp; Angular demonstration app</h2>
      <br/><img src='assets/img/face-5.svg' class='aboutface bounce'/><br/><br/>
    </div>
  </div>
</div>


<div class="panel panel-primary simpleFadeIn">
  <div class="panel-heading">
    <h2 class="panel-title">Info</h2>
  </div>
  <div class="panel-body">
    <h4>Version: v2.1.2</h4>
    <h4>&copy; Ben Coleman, 2018</h4>
    <hr/>
    <table>
      <tr>
        <td>Angular Mode: &nbsp;</td><td>{{ devMode }}</td>
      </tr>
      <tr>
        <td>Secured: &nbsp;</td><td>{{ secured }}</td>
      </tr>
      <tr>
        <td>API Endpoint: &nbsp;</td><td>{{ apiEndpoint }}</td>
      </tr>
      <tr>
        <td>More System Info : &nbsp;</td><td><a target="_blank" href="{{ apiEndpoint }}/info">{{ apiEndpoint }}/info</a></td>
      </tr>      
    </table>
  </div>
</div>


<div class="panel panel-primary simpleFadeIn">
  <div class="panel-heading">
    <h2 class="panel-title">Links</h2>
  </div>
  <div class="panel-body" style="font-size:100%">
    <ul>
      <li><a href='https://aka.ms/smilr-project' target='_blank'>GitHub Project Page &amp; Source</a></li>
      <li><a href='https://aka.ms/smilr-devops'  target='_blank'>CI/CD Build &amp; Release Pipelines</a></li>
    </ul>
  </div>
</div>
