// vue/src/App.vue
<template v-if="ok">
  <div id="app">
    <b-navbar toggleable="md" type="dark" variant="primary">
      <b-navbar-toggle target="nav_collapse" />

      <b-navbar-brand :to="{name:'home'}" style="font-size:32px;">
        <img src="@/assets/img/logo-white.svg" class="logo"> &nbsp;Smilr
      </b-navbar-brand>
      <b-collapse id="nav_collapse" is-nav>
        <b-navbar-nav>
          <b-button size="lg" :to="{name:'events'}" class="bigger" variant="success">
            <fa icon="coffee" /> Events
          </b-button>
            &nbsp; &nbsp;
          <b-button size="lg" :to="{name:'about'}" class="bigger" variant="success">
            <fa icon="info-circle" /> About
          </b-button>
        </b-navbar-nav>

        <b-navbar-nav class="ml-auto">
          <b-button size="lg" :to="{name:'report'}" class="bigger" variant="warning">
            <fa icon="chart-bar" /> Report
          </b-button>
            &nbsp;&nbsp;
          <b-button size="lg" :to="{name:'admin'}" class="bigger" variant="warning">
            <fa icon="tools" /> Admin
          </b-button>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>

    <br>

    <b-container>
      <router-view />
    </b-container>

    <!-- User details button in footer -->
    <div class="appFooter">
      <b-button v-if="user()" v-b-modal.userModal variant="outline-primary">
        <fa icon="user" /> {{ user().userName }}
      </b-button>
      <b-button v-else disabled variant="outline-primary">
        No user logged in
      </b-button>
    </div>

    <!-- Popup modal used by the user button -->
    <b-modal v-if="user()" id="userModal" title="User Details" ok-only>
      <p>Name: {{ user().name }}</p>
      <p>User Name: {{ user().userName }}</p>
      <b-button variant="warning" @click="authLogout">
        Logout
      </b-button>
    </b-modal>
  </div>
</template>

<script>
import auth from './mixins/auth'

export default {
  name: 'App',
  mixins: [ auth ],
}
</script>

<style>
  .appFooter {
    width: 100%;
    text-align: right;
    margin-top: 0.5rem;
    padding: 0.8rem;
    border-top: 1px solid #ddd;
    color: #999
  }
  .logo {
    height: 45px;
  }
  .bigger {
    font-size: 1.4rem !important;
    margin-right: 10px !important;
  }
</style>

// angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { environment } from '../environments/environment';
import { UserService } from './admin/user.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'app'; 
  
  public env = environment;
  public userService: UserService;
  @ViewChild('sideNav') public sideNav;

  constructor(us: UserService) {
    this.userService = us;
  }
}

     
<div>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">

      <!-- sidebar only show when toggled/opened -->
      <side-nav #sideNav [env]="env" [userService]="userService" [aboutDialog]="aboutDialog"></side-nav>

      <!-- logo -->
      <a class="navbar-brand" [routerLink]="['/home']"><img src='assets/img/logo-white.svg' class="navlogo"> <span class="navlogotext">&nbsp;Smilr</span> </a>

      <!-- left hand buttons (hidden when mobile) -->
      <ul class="nav navbar-nav navbar-left hidden-xs">
        <li>
          <p class="navbar-btn"><a class="btn btn-success" [routerLink]="['/events']"><i class="fa fa-book"></i> <span class="hidden-sm"> Events</span></a>&nbsp;</p>
        </li>
        <li>
         <p class="navbar-btn"><a class="btn btn-success" (click)="aboutDialog.show()"><i class="fa fa-info-circle"></i> <span class="hidden-sm"> About</span></a>&nbsp;</p>
        </li>
      </ul>

      <!-- ADMIN right hand buttons (hidden when mobile) -->
      <ul class="nav navbar-nav navbar-right hidden-xs" *ngIf="!env.secured || userService.isLoggedIn()">
        <li>
          <p class="navbar-btn"><a class="btn btn-warning" [routerLink]="['/admin/report']"><i class="fa fa-bar-chart"></i> <span class="hidden-sm"> Reports</span></a>&nbsp;</p>
        </li>
        <li>
          <p class="navbar-btn"><a class="btn btn-warning" [routerLink]="['/admin/events']"><i class="fa fa-wrench"></i> <span class="hidden-sm"> Admin</span></a>&nbsp;</p>
        </li>
        <li>
          <p class="navbar-btn"><a class="btn btn-warning" href='/.auth/logout/aad'><i class="fa fa-user-circle"></i> <span class="hidden-md hidden-sm"> Logout</span></a>&nbsp;</p>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right hidden-xs" *ngIf="env.secured && !userService.isLoggedIn()">
        <li>
          <p class="navbar-btn"><a class="btn btn-warning" href='/.auth/login/aad?post_login_redirect_uri=/logincomplete'><i class="fa fa-user"></i> Login</a>&nbsp;</p>
        </li>
      </ul>

      <!-- toggle sidenav menu button (only shown on mobile) -->
      <div class="nav navbar-nav pull-right visible-xs" >
        <button type="button" class="btn btn-primary menubars" (click)="sideNav.toggle()">
          <i class="fa fa-bars"></i>
        </button>
        &nbsp;
      </div>

    </div>
  </nav>

  <main>
    <router-outlet></router-outlet>
  </main>

  <footer>
    <div *ngIf="env.secured">Security enabled</div> <div *ngIf="!env.secured">Security disabled (demo mode)</div> 
    <div *ngIf="userService.isLoggedIn()">You are logged in as: {{ userService.getUserId() }}</div>
  </footer>

</div>

<!-- About dialog -->
<modal-dialog #aboutDialog dialogTitle="Smilr" hideCancel="true" dialogBody="<div class='about'>
  <img src='assets/img/face-5.svg' class='aboutface bounce'/><br/><br/><h4>A microservices &amp; Angular demonstration app</h4></div>
  v2.0.3<br/>
  <a href='https://github.com/benc-uk/microservices-demoapp' target='_blank'>github.com/benc-uk/microservices-demoapp</a>
  <br/>&copy; Ben Coleman, 2018" ></modal-dialog>
