// vue/src/components/Home.vue
<template>
  <div>
    <h1>Currently Active Events</h1>
    <event-list filter="active"></event-list>
    
    <br/><br/>

    <h1>Upcoming Future Events</h1>
    <event-list filter="future"></event-list>
  </div>
</template>

<script>
import EventList from './EventList'

export default {
  name: 'Home',
  
  components: {
    'event-list': EventList
  },
}
</script>

// angular/src/app/home.component.ts
import { Component } from '@angular/core';

@Component({
  template: `
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h3>&nbsp; Active Events</h3>
      <event-list time="active">
      </event-list>
    </div>

    <hr/>
    
    <div class="col-md-10 col-md-offset-1">
      <h3>&nbsp; Upcoming Events</h3>
      <event-list time="future">
      </event-list> 
    </div>
  </div> 
  `
})

export class HomeComponent  {
}
